@startuml
'https://plantuml.com/class-diagram

class Solution42
{
-firstnames , lastnames, salary: ArrayList<String>
-count: int
-space1 and space2: String
+main()
+obj = Read() object

}
class Read
{
-fname , lname, money: ArrayList<String>
-count: int
+get_firstnames()
+get_lastnames()
+get_salary()
+get_count()
}

Solution42 "get names(first and last), salary, and count from Read()" --- Read

@enduml