@startuml
'https://plantuml.com/class-diagram

class Solution45
{
-oldtext, replacedtext, output_file_name: String
+main()
+r = Read() object
+w = Write() object

}
class Read
{
-line, oldtext and replaced: String
+get_old_text()
+get_replaced_text()
}
class Write
{
+open_file()
}

Solution45 "get old and new texts from Read()" --- Read
Solution45 "use Write() to create output file"--- Write

@enduml